apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
